apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "opensearch-cluster-hot-pdb"
  labels:
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/instance: opensearch-cluster-hot
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opensearch
      app.kubernetes.io/instance: opensearch-cluster-hot

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "opensearch-cluster-warm-pdb"
  labels:
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/instance: opensearch-cluster-warm
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opensearch
      app.kubernetes.io/instance: opensearch-cluster-warm
