kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: argo-events

resources:
- argo-events

patchesStrategicMerge:

  - |-
    apiVersion: argoproj.io/v1alpha1
    kind: EventBus
    metadata:
      name: default
    spec:
      nats:
        native:
          containerTemplate:
            resources:
              requests:
                memory: "50Mi"
                cpu: "10m"
              limits:
                memory: "100Mi"
                cpu: "30m"
          metricsContainerTemplate:
            resources:
              requests:
                memory: "50Mi"
                cpu: "10m"
              limits:
                memory: "100Mi"
                cpu: "30m"

  - |-
    apiVersion: argoproj.io/v1alpha1
    kind: Sensor
    metadata:
      name: prom-webhook
    spec:
      template:
        container:
          resources:
            requests:
              cpu: "10m"
              memory: "50Mi"
            limits:
              cpu: "30m"
              memory: "100Mi"

  - |-
    apiVersion: argoproj.io/v1alpha1
    kind: Sensor
    metadata:
      name: webhook
    spec:
      template:
        container:
          resources:
            requests:
              cpu: "10m"
              memory: "50Mi"
            limits:
              cpu: "30m"
              memory: "100Mi"

  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: controller-manager
      labels:
        app: controller-manager
    spec:
      template:
        spec:
          containers:
          - name: controller-manager
            resources:
              requests:
                memory: "50Mi"
                cpu: "10m"
              limits:
                memory: "100Mi"
                cpu: "30m"
